version: '3'

services:
  rapJeuDB:
    container_name: rapJeuDB
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: rapjeu
      POSTGRES_USER: rapjeu
    ports:
      - 5432:5432
  communityDB:
    container_name: communityDB
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: community
      POSTGRES_USER: community
    ports:
      - 5433:5432
